---
#sudo add-apt-repository ppa:deadsnakes/ppa
- name: Add python repository for python3.6
  apt_repository:
    repo: 'ppa:deadsnakes/ppa'
    state: present

#sudo apt-get install python3.6
- name: Install django prerequisites
  apt: pkg={{item}} state=present
  with_items:
    - python3.6
    - python3.6-dev
    - python3.6-venv
