image: docker:19.03.8

variables:
  DOCKER_TLS_CERTDIR: "/certs"
  POSTGRES_HOST: 'db'
  POSTGRES_DB: "my_custom_db"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "example"

services:
  - docker:19.03.8-dind

before_script:
- docker info
- curl -L "https://github.com/docker/compose/releases/download/1.25.5/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

build:
  stage: build
  script:
    - docker build -f docker/Dockerfile -t dirkcuys/unhangout .
    - docker-compose -f docker/docker_compose.yml run test
