version: '3'
services:
  email:
    image: djfarrelly/maildev
    ports:
    - "1080:80"
    - "1025:25"
    networks:
    - unhangout
  redis:
    image: redis
    ports:
    - 6379:6379
    networks:
    - unhangout
  postgres:
    image: postgres:11
    environment:
    - POSTGRES_PASSWORD=password
    - POSTGRES_HOST_AUTH_METHOD=password
    ports:
    - "5432:5432"
    networks:
    - unhangout
  memcached:
    image: memcached
    networks:
    - unhangout
  etherpad:
    image: dirkcuys/hangpad
    #image: etherpad/etherpad
    depends_on:
    - postgres
    volumes:
    - ./docker/settings.json:/opt/etherpad-lite/settings.json
    - ./docker/APIKEY.txt:/opt/etherpad-lite/APIKEY.txt
    ports:
    - 9001:9001
    environment:
    - ADMIN_PASSWORD=password
    - NODE_ENV=production
    - DB_TYPE=postgres
    - DB_HOST=postgres
    - DB_USER=postgres
    - DB_PASS=password
    - DB_NAME=etherpad
    networks:
    - unhangout
  frontend:
    build:
      dockerfile: docker/Dockerfile.frontend
      context: .
    volumes:
    - ./reunhangout:/opt/app/
  unhangout:
    build: .
    image: local/unhangout:latest
    depends_on:
    - postgres
    - redis
    - email
    - memcached
    - etherpad
    - frontend
    volumes:
    - ./reunhangout:/opt/app/
    ports:
    - 8000:8000
    env_file: ./docker/env
    environment:
    - DEBUG=true
    - DOMAIN=localhost
    - POSTGRES_HOST=postgres
    - POSTGRES_DB=unhangout
    - POSTGRES_USER=unhangout
    - POSTGRES_PASSWORD=password
    - EMAIL_HOST=email
    - REDIS_HOST=redis
    - ETHERPAD_SERVER=http://etherpad:9001
    - ETHERPAD_API_KEY=thisreallydoesntmattermuch
    - BROKER_URL=redis://redis:6379/0
    - MEMCACHED_HOST=memcached
    networks:
    - unhangout
    command: /opt/app-venv/bin/python manage.py runserver 0.0.0.0:8000
  celery:
    image: local/unhangout:latest
    depends_on:
    - postgres
    - redis
    - email
    - memcached
    user: celery
    env_file: ./docker/env
    environment:
    - DOMAIN=localhost
    - POSTGRES_HOST=postgres
    - POSTGRES_DB=unhangout
    - POSTGRES_USER=unhangout
    - POSTGRES_PASSWORD=password
    - EMAIL_HOST=email
    - REDIS_HOST=redis
    - ETHERPAD_SERVER=http://etherpad:9001
    - BROKER_URL=redis://redis:6379/0
    - MEMCACHED_HOST=memcached
    volumes:
    - ../reunhangout:/opt/app/
    networks:
    - unhangout
    command: /opt/app-venv/bin/celery worker -A reunhangout --loglevel=debug
  selenium:
    image: selenium/standalone-chrome
    networks:
    - unhangout
  test:
    image: local/unhangout:latest
    command: /opt/app-venv/bin/pytest -vv
    depends_on:
    - postgres
    - redis
    - email
    - memcached
    - selenium
    volumes:
    - ../reunhangout:/opt/app/
    env_file: ./docker/env
    environment:
    - DOMAIN=localhost
    - POSTGRES_HOST=postgres
    - EMAIL_HOST=email
    - REDIS_HOST=redis
    - ETHERPAD_SERVER=http://etherpad:9001
    - BROKER_URL=redis://redis:6379/0
    - MEMCACHED_HOST=memcached
    networks:
    - unhangout
networks:
  unhangout:
