---
# Set up nagios and munin client stuff.  NOTE: You still need to add the host
# that is monitored to ``nagios_and_munin_generated_configs``; or manually
# write nagios monitoring config and add to ``munin_domains``.

- name: "Install base packages"
  apt: 
    state: present
    pkg:
    - nagios-nrpe-server
    - monitoring-plugins-basic
  tags: monitored

- name: "Install nagios-nrpe local config"
  template: >
    src="{{monitoring_nrpe_template}}"
    dest=/etc/nagios/nrpe_local.cfg
    owner=root
    group=root
    mode=0644
  notify: restart nagios-nrpe-server
  tags: monitored

- name: "Open nagios ports"
  command: ufw allow proto tcp from {{monitoring_server_ip}} to any port 5666
  register: ufw_result
  changed_when: "ufw_result.stdout.startswith('Rule')"
  tags: monitored

#   - name: "Copy check-reboot-required script"
#     copy: >
#       src=usr_local_bin_check-reboot-required
#       dest=/usr/local/bin/check-reboot-required
#       mode=0755
#       owner=root
#       group=root
#     tags: monitored
