---
- name: Tarsnap src dir
  file: state=directory path=/usr/local/src/tarsnap

- name: Tarsnap backup script
  template: src=tarsnap.py dest=/usr/local/src/tarsnap

- name: copy Dockerfile for tarnsap
  copy:
    src: Dockerfile
    dest: /usr/local/src/tarsnap

- name: build docker image to run tarsnap
  docker_image:
    name: unhangout/tarsnap
    build:
      path: /usr/local/src/tarsnap
      pull: yes
    tag: latest
    source: build
    force_source: yes
    state: present

# Configuration
- name: Create env file
  template:
    src: tarsnap.env
    dest: /root/tarsnap.env
    owner: root
    group: root
    mode: 0600

- name: Tarsnap key
  copy:
    content="{{tarsnap_key}}"
    dest="/root/tarsnap.key"
    owner=root
    group=root
    mode=0600
    force=no

#- name: Tarsnap cache directory
#file: state=directory path="{{tarsnap_cache}}"
#tags: ['tarsnap']

- name: Tarsnap cron
  cron:
    name: "Tarsnap backup"
    minute: "11"
    hour: "23"
    job: >
        docker run --rm --env-file /root/tarsnap.env 
        -v /root/tarsnap.key:/root/tarsnap.key
        -v /var/docker-volumes/nginx/static/{{django_domain}}/media:/unhangout/media:ro
        -v /var/docker-volumes/tarsnap/cache:/tarsnap/cache
        --link postgres:postres
        unhangout/tarsnap
    state: present
