---
## REQUIRED. Override these:

# String contents of tarnsap key. Probably store in ansible-vault.
tarsnap_key: ""

## OPTIONAL. Override the following if you want. You probably at least want to
## override `tarsnap_dirs`.

# Version of tarsnap to target
tarsnap_version: "1.0.36.1"

# Directories to back up, relative to '/', e.g. 
#  - "home/user"
#  - "var/lib/mailboxes"
tarsnap_dirs: []

# Names of postgres databases to dump then backup.
tarsnap_postgres_databases: []

# Cron settings for when to execute backups.
tarsnap_cron_disabled: no
tarsnap_cron_month: "*"
tarsnap_cron_day: "*"
tarsnap_cron_hour: "23"
tarsnap_cron_minute: "11"

# Path to tarsnap cache
tarsnap_cache: "/usr/local/tarsnap-cache"

# Path to file to store tarsnap key in
tarsnap_key_path: "/root/tarsnap.key"

# Path to file to store tarsnap script in
tarsnap_script_path: "/root/tarsnap.py"

# Extra flags to invoke tarsnap with (array)
tarsnap_extra_flags: ["--verylowmem"]

# Absolute path to temporary directory into which to dump postgres dumps prior
# to backup. This directory will be the path they are restored to as well.
tarsnap_postgres_tmp_dir: "/tmp/postgres_backups/"
