---
#- name: create etherpad user to reserver uid

- name: create dir for etherpad
  file: path=/var/docker-volumes/etherpad state=directory

# uh_etherpad_session_key
- name: create session key
  copy:
    dest: /var/docker-volumes/etherpad/SESSIONKEY.txt
    content: "{{uh_etherpad_session_key}}"
    mode: "640"
    owner: "5001"

# uh_etherpad_api_key
- name: create api key
  copy:
    dest: /var/docker-volumes/etherpad/APIKEY.txt
    content: "{{uh_etherpad_api_key}}"
    mode: "640"
    owner: "5001"

- name: start docker container
  docker_container:
    name: "{{etherpad_domain}}"
    image: "etherpad/etherpad"
    state: started
    pull: yes
    restart: yes
    restart_policy: always
    links:
    - "postgres:postgres"
    volumes:
    - /var/docker-volumes/etherpad/APIKEY.txt:/opt/etherpad-lite/APIKEY.txt
    - /var/docker-volumes/etherpad/SESSIONKEY.txt:/opt/etherpad-lite/SESSIONKEY.txt
    env:
      VIRTUAL_HOST: "{{etherpad_domain}}"
      LETSENCRYPT_HOST: "{{etherpad_domain}}"
      LETSENCRYPT_EMAIL: "{{admin_email}}"
      DOMAIN: "{{etherpad_domain}}"
      TITLE: "Unhangout"
      DB_TYPE: postgres
      DB_HOST: postgres
      DB_NAME: "{{etherpad_db_name}}"
      DB_USER: "{{etherpad_db_username}}"
      DB_PASS: "{{etherpad_db_password}}"
      TRUST_PROXY: "true"
      IMPORT_EXPORT_RATE_LIMIT_WINDOW: "15000"
      IMPORT_EXPORT_MAX_REQ_PER_IP: "100"
