---
- hosts: all
  become: yes
  become_user: root
  vars_files:
   - vars/secrets.yml
   - vars/staging-secrets.yml
  tasks:
   - service: name=reunhangout state=restarted
   - service: name=reunhangout-celery state=restarted
   - service: name=reunhangout-celery-beat state=restarted
   - service: name=reunhangout-interface state=restarted
