---
- hosts: all
  become: yes
  become_user: root
  vars_files:
   - vars/secrets.yml
  tasks:
   - name: Restart workers
     service: name=reunhangout-workers.target state=restarted
   - name: Restart interface
     service: name=reunhangout-interface state=restarted
   - name: Restart celery
     service: name=reunhangout-celery state=restarted
   - name: Restart celery beat
     service: name=reunhangout-celery-beat state=restarted
