---
- name: Increase open file descriptor limit for nginx
  lineinfile:
    name: /etc/nginx/nginx.conf
    regexp: '^worker_rlimit_nofile'
    line: 'worker_rlimit_nofile 65535;'
    insertafter: '^worker_processes'
    state: present
  tags: ['reunhangout', 'reunhangout-post']

- block:
  - name: Copy websocket worker service template
    template: >
      src=reunhangout-worker-websocket.service
      dest=/usr/lib/systemd/system/reunhangout-worker-websocket.service
    notify: >
      - systemctl daemon-reload
      - restart reunhangout-worker-websocket

  - name: Enable websocket worker
    command: systemctl enable reunhangout-worker-websocket.service
    register: systemd_enable
    changed_when: systemd_enable.stdout.find("Created") != -1
  tags: ['reunhangout', 'reunhangout-post']
  
- name: Build prod assets
  become: yes
  become_user: "{{main_user_name}}" 
  command: "{{django_project_dir}}build_prod_assets.sh"
  register: build_prod_assets
  changed_when: build_prod_assets.stdout.find("Changed") != -1
  notify: restart {{django_init_name}}
  tags: ['reunhangout', 'reunhangout-post', 'djangocode']

- name: Sync auth providers
  command: "{{django_venv_dir}}bin/python {{django_project_dir}}manage.py sync_auth_providers"
  register: sync_auth_providers
  changed_when: sync_auth_providers.stdout.find("changed") != -1
  tags: ['reunhangout', 'reunhangout-post']

- name: Collect static again
  become: yes
  become_user: "{{main_user_name}}" 
  register: collectstatic_output
  changed_when: 'not collectstatic_output.stdout.startswith("\n0 static files copied")'
  command: "{{django_venv_dir}}bin/python {{django_project_dir}}manage.py collectstatic --noinput"
  tags: ['reunhangout', 'reunhangout-post', 'djangocode']
