---
 - name: Sync auth providers
   command: "{{django_venv_dir}}bin/python {{django_project_dir}}manage.py sync_auth_providers"
   register: sync_auth_providers
   changed_when: sync_auth_providers.stdout.find("changed") != -1
   tags: ['reunhangout', 'reunhangout-post']

 - name: Build prod assets
   command: "{{django_project_dir}}build_prod_assets.sh"
   register: build_prod_assets
   changed_when: build_prod_assets.stdout.find("Changed") != -1
   notify: restart {{django_init_name}}
