---
 - name: Sync auth providers
   command: "{{django_venv_dir}}bin/python {{django_project_dir}}manage.py sync_auth_providers"
   register: sync_auth_providers
   changed_when: sync_auth_providers.stdout.find("changed") != -1
   tags: ['reunhangout', 'reunhangout-post']
