---
- name: systemctl daemon-reload
  command: systemctl daemon-reload

- name: restart disable-thp
  systemd: name=disable-thp state=restarted

- name: restart redis
  service: name=redis state=restarted
 
